### ISSUE TITLE
Set template objective error

### ISSUE THREAD

**Issue by marcelo-maciel** [sergiovision/FinCore#3]
Hi Sergio!

I added COGN3 to Metasymbol
added Objective.ex5 to MQL5 >> Profiles >> Templates, 
Added FileHistoryData.ex5, IndicatorBars.tpl, Indicators.tpl to \MQL5\experts
Rigth click on chart COGN3 with D1 timeframe, then on Experts tab, show these logs:

2020.08.16 03:16:08.573	Objective (COGN3,D1)	 213
2020.08.16 03:16:08.573	Objective (COGN3,D1)	InitExpert(1061718451, PERIOD_D1, COGN3) FAILED!!! No Magic Number returned!!
2020.08.16 03:16:08.576	Objective (COGN3,D1)	Expert <COGN3> closed with reason 8 <REASON_INITFAILED> This value means that _OnInit()_ handler has returned a nonzero value At 2020.08.14 17:54.
2020.08.16 03:16:08.581	Objective (COGN3,D1)	2 undeleted objects left
2020.08.16 03:16:08.581	Objective (COGN3,D1)	1 object of type ExpertParams left
2020.08.16 03:16:08.581	Objective (COGN3,D1)	1 object of type CJAVal left
2020.08.16 03:16:08.581	Objective (COGN3,D1)	14246 bytes of leaked memory

Can you help me?

**Comment by sergiovision** [comment]
Hi Marcelo, read documentation first http://localhost:4200/fincore/#/doc
Documentation says for this case: 
To add Adviser on a chart just right click and selet Objective template. FinCore will make all the rest.
But before adding template make sure you have added this symbol into Metasymbols management screen.
You should add Metasymbol  Add COGN3
And then add Symbol on Symbol Tab COGN3
Then Adviser can find this symbol in the database and create Expert in the database for that symbol.
If symbol is not registered in the database you will always get an error you shown.

**Comment by marcelo-maciel** [comment]
Solved! @feliperails sugested replace localhost for 127.0.0.1 on Fincore server/client and works!
