### ISSUE TITLE
SSA Fast Trend Forecast - failed to load

### ISSUE THREAD

**Issue by marcelo-maciel** [sergiovision/FinCore#4]
I downloaded and install SSA Fast Trend Forecast, with link below, but when load , the fail occurs.
https://www.mql5.com/pt/market/product/18088

2020.08.24 19:00:47.595	Objective (COGN3,M1)	Indicator Market\SSA Fast Trend Forecast - failed to load!!!!!!!!!!!!!

Is required for any reason?

**Comment by sergiovision** [comment]
No this indicator is not needed. It is just another indicator, I made it built in and loaded by default. Will make it optional in future releases.

**Comment by sergiovision** [comment]
Issue fixed in this tag https://github.com/sergiovision/FinCore/releases/tag/v0.9.4
