### ISSUE TITLE
MetaTrader file with source

### ISSUE THREAD

**Issue by codingopedia** [sergiovision/FinCore#6]
Hello, 
You can provide source files for .ex5, I would like to use them for MT4 platform too

**Comment by sergiovision** [comment]
Sorry sources are not free as I invested much time in development of the project. $100 is the price for sources. 50$ for help with setup application on VPS server.
Also sources now support only MQL5. I removed support of MQL4 and removed MQL4 functions/classes versions from codebase. 
But initially both MT4/MT5 supported and I have no time and will to support MT4 version as it is an obsolete platform.

**Comment by sergiovision** [comment]
MT4 will not be supported as it is an obsolete platform.
